dataSource: !file
  demandDataFolder: output/demand-data-local
  matrixConfigurationFile: data/slis/input/matrix-configuration.yaml
  attractivityDataFile: data/schaufenster/input/Strukturdaten_Stuttgart_2009_Attractivities.csv
  #charging: unlimited
  defaultChargingPower: config/ChargingPower.txt
days: 1
destinationChoice:
  repetition: config/TargetParameterRepetition2.csv
  work: config/DestinationAndModeChoiceParameterSchaufenster_1.txt
  business: config/DestinationAndModeChoiceParameterSchaufenster_2.txt
  education: config/DestinationAndModeChoiceParameterSchaufenster_3.txt
  service: config/DestinationAndModeChoiceParameterSchaufenster_6.txt
  home: config/DestinationAndModeChoiceParameterSchaufenster_7.txt
  undefined: config/DestinationAndModeChoiceParameterSchaufenster_8.txt
  otherhome: config/DestinationAndModeChoiceParameterSchaufenster_9.txt
  privateBusiness: config/DestinationAndModeChoiceParameterSchaufenster_11.txt
  privateVisit: config/DestinationAndModeChoiceParameterSchaufenster_12.txt
  shoppingDaily: config/DestinationAndModeChoiceParameterSchaufenster_41.txt
  shoppingOther: config/DestinationAndModeChoiceParameterSchaufenster_42.txt
  leisureIndoor: config/DestinationAndModeChoiceParameterSchaufenster_51.txt
  leisureOutdoor: config/DestinationAndModeChoiceParameterSchaufenster_52.txt
  leisureOther: config/DestinationAndModeChoiceParameterSchaufenster_53.txt
  leisureWalk: config/DestinationAndModeChoiceParameterSchaufenster_77.txt
fractionOfPopulation: 0.01
#numberOfZones: 1174
resultFolder: results/simulation
seed: 1234
visumFile: data/stuttgart_2009_everkehrsraum_nutzung.net.bz2
#experimental:
#  parameter1: 1
#  parameter2: 2